all:
  hosts:
    master1:
      ansible_host: 192.168.1.44
      ip: 192.168.1.44
      access_ip: 192.168.1.44
    master2:
      ansible_host: 192.168.1.42
      ip: 192.168.1.42
      access_ip: 192.168.1.42
    worker1:
      ansible_host: 192.168.1.45
      ip: 192.168.1.45
      access_ip: 192.168.1.45
    worker2:
      ansible_host: 192.168.1.34
      ip: 192.168.1.34
      access_ip: 192.168.1.34
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
    kube_node:
      hosts:
        master1:
        master2:
        worker1:
        worker2:
    etcd:
      hosts:
        master1:
        master2:
        worker1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
